FROM golang:1.24-bookworm AS build

RUN apt-get update && apt-get install --yes --no-install-recommends \
    libgl1-mesa-dev \
    libxcursor-dev \
    libxi-dev \
    libxinerama-dev \
    libxrandr-dev \
    libxxf86vm-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN go build -o /out/domino-frame-arm .

FROM scratch

COPY --from=build /out/domino-frame-arm /domino-frame-arm
